services:
  website:
    container_name: website
    
    image: website:latest
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - proxy
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`kotalos.localhost`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true