services:
  website:
    container_name: website
    image: ghcr.io/kotalos/website:main
    networks:
      - proxy
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`kotalos.localhost`) || Host(`kotalos.com`) || Host(`sphynx.kotalos.com`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true